default_agent: reciperecommendationagent
agents:
  reciperecommendationagent:
    name: reciperecommendationagent
    entrypoint: C:/Users/rksha/sk_git_hub_projects/recipe-recommendation-agent/recipeRecommendationAgent/src/main.py
    deployment_type: container
    runtime_type: PYTHON_3_10
    platform: linux/arm64
    container_runtime: null
    source_path: C:\Users\rksha\sk_git_hub_projects\recipe-recommendation-agent\recipeRecommendationAgent\src
    aws:
      execution_role: arn:aws:iam::334966104707:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-40a11ed03e
      execution_role_auto_create: false
      account: '334966104707'
      region: us-east-1
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-334966104707-us-east-1
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: RecipeRecommendationAgent-Yb7AknBRii
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:334966104707:runtime/RecipeRecommendationAgent-Yb7AknBRii
      agent_session_id: null
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: STM_AND_LTM
      memory_id: RecipeRecommendationAgent_mem-hCDVr5Foji
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:334966104707:memory/RecipeRecommendationAgent_mem-hCDVr5Foji
      memory_name: RecipeRecommendationAgent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration:
      requestHeaderAllowlist:
      - X-Amzn-Bedrock-AgentCore-Runtime-Custom-User-Id
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: true
